const khmerAddresses = [
    "Phnom Penh, Daun Penh",
    "Phnom Penh, Chamkarmon",
    "Phnom Penh, Toul Kork",
    "Phnom Penh, Dangkao",
    "Phnom Penh, Mean Chey",
    "Phnom Penh, Russey Keo",
    "Phnom Penh, Sen Sok",
    "Phnom Penh, Prampir Makara",
    "Phnom Penh, Tuol Svay Prey",
    "Phnom Penh, Chbar Ampov",
    "Phnom Penh, Por Sen Chey",
    "Phnom Penh, Chroy Changvar",
    "Phnom Penh, Russei Keo",
    "Phnom Penh, Boeng Keng Kang",
    "Phnom Penh, Srah Chak",
    "Phnom Penh, Doun Penh",
    "Phnom Penh, Boeung Keng Kang",
    "Phnom Penh, Toul Tum Poung",
    "Phnom Penh, Sra Nge",
    "Phnom Penh, Teuk Laak 1",
    "Phnom Penh, Teuk Laak 2",
    "Phnom Penh, Teuk Thla",
    "Phnom Penh, Boeung Prolit",
    "Phnom Penh, Boeung Trabek",
    "Phnom Penh, Tonle Bassac",
    "Phnom Penh, Phsar Chas",
    "Phnom Penh, Phsar Kandal",
    "Phnom Penh, Phsar Thmei",
    "Phnom Penh, Prey Sar",
    "Phnom Penh, Prey Veng",
    "Phnom Penh, Ruessei Keo",
    "Phnom Penh, Samraong Kraom",
    "Phnom Penh, Boeng Salang",
    "Phnom Penh, Boeng Tompun",
    "Phnom Penh, Chak Angrae Leu",
    "Phnom Penh, Chak Angrae Kraom",
    "Phnom Penh, Chbar Ampov",
    "Phnom Penh, Chaom Chao",
    "Phnom Penh, Chey Chumneah",
    "Phnom Penh, Chraoy Changva",
    "Phnom Penh, Dangkao",
    "Phnom Penh, Dei Eth",
    "Phnom Penh, Nirouth",
    "Phnom Penh, Preaek Lieb",
    "Phnom Penh, Preaek Pra",
    "Phnom Penh, Preaek Thmei",
    "Phnom Penh, Preaek Thmey",
    "Phnom Penh, Preaek Aeng",
    "Phnom Penh, Preaek Kambot",
    "Phnom Penh, Preaek Leab",
    "Phnom Penh, Preaek Phnov",
    "Phnom Penh, Preaek Russey",
    "Phnom Penh, Preaek Thloeng",
    "Phnom Penh, Preaek Tapov",
    "Phnom Penh, Preaek Tasek",
    "Phnom Penh, Preaek Thmei",
    "Phnom Penh, Preaek Aeng",
    "Phnom Penh, Preaek V",
    "Phnom Penh, Prey Sa",
    "Phnom Penh, Prey Sa",
    "Phnom Penh, Prey Sar",
    "Phnom Penh, Prey Topeang",
    "Phnom Penh, Prey Veng",
    "Phnom Penh, Prum Bey",
    "Phnom Penh, Punnhea Krek",
    "Phnom Penh, Pursat",
    "Phnom Penh, Roka Kaoh",
    "Phnom Penh, Roluos",
    "Phnom Penh, Rong Chak",
    "Phnom Penh, Rong Chak",
    "Phnom Penh, Rong Krang",
    "Phnom Penh, Rong Roeurng",
    "Phnom Penh, Russey Keo",
    "Phnom Penh, Russey Sanh",
    "Phnom Penh, Russey Sen",
    "Phnom Penh, Russey Srok",
    "Phnom Penh, Ruessei Kraom",
    "Phnom Penh, Ruessei Srok",
    "Phnom Penh, Saen Sokh",
    "Phnom Penh, Samraong",
    "Phnom Penh, Samraong Kandal",
    "Phnom Penh, Samraong Tong",
    "Phnom Penh, Samraong Toul",
    "Phnom Penh, Santhor Muk",

    "Siem Reap, Siem Reap City",
    "Siem Reap, Angkor Thom",
    "Siem Reap, Angkor Wat",
    "Siem Reap, Banteay Srei",
    "Siem Reap, Banteay Samre",
    "Siem Reap, Roluos",
    "Siem Reap, Tonle Sap",
    "Siem Reap, Chong Kneas",
    "Siem Reap, Phnom Kulen",
    "Siem Reap, Preah Khan",
    "Siem Reap, Ta Prohm",
    "Siem Reap, Bayon",

    "Kampong Cham, Kampong Cham City",
    "Kampong Cham, Batheay",
    "Kampong Cham, Chamkar Leu",
    "Kampong Cham, Kang Meas",
    "Kampong Cham, Koh Sotin",
    "Kampong Cham, Prey Chhor",
    "Kampong Cham, Stueng Trang",
    "Kampong Cham, Veal Veng",
    "Kampong Cham, Cheung Prey",
    "Kampong Cham, Tbong Khmum",
    "Kampong Cham, Memot",
    "Kampong Cham, Ou Reang Ov",
    "Kampong Cham, Ponhea Kraek",
    "Kampong Cham, Kampong Siem",
    "Kampong Cham, Chikreng",
    "Kampong Cham, Snoul",
    "Kampong Cham, Kroch Chhmar",
    "Kampong Cham, Chamkar Leu",
    "Kampong Cham, Kampong Cham Thmey",
    "Kampong Cham, Memot",
    "Kampong Cham, Prey Chhor",
    "Kampong Cham, Srei Santhor",
    "Kampong Cham, Stueng Trang",
    
    "Battambang, Battambang City",
    "Battambang, Banan",
    "Battambang, Ek Phnom",
    "Battambang, Kors Kralor",
    "Battambang, Moung Ruessei",
    "Battambang, Ou Ta Ki",
    "Battambang, Rotanak Mondol",
    "Battambang, Samlout",
    "Battambang, Sangkae",
    "Battambang, Thma Koul",
    "Battambang, Bavel",
    "Battambang, Phnum Proek",
    "Battambang, Sdao",
    "Battambang, Ta Kream",
    "Battambang, Wat Kor",
    "Battambang, Wat Kor",
    "Battambang, Phnum Proek",

    "Banteay Meanchey, Paoy Paet City",
    "Banteay Meanchey, Seri Saophoan City",
    "Banteay Meanchey, Mongkol Borei",
    "Banteay Meanchey, Phnum Srok",
    "Banteay Meanchey, Preah Netr Preah",
    "Banteay Meanchey, Ou Chrov",
    "Banteay Meanchey, Thma Puok",
    "Banteay Meanchey, Svay Chek",
    "Banteay Meanchey, Malai",

    "Kampong Chhnang, Kampong Chhnang City",
    "Kampong Chhnang, Baribour",
    "Kampong Chhnang, Chol Kiri",
    "Kampong Chhnang, Kampong Leaeng",
    "Kampong Chhnang, Kampong Tralach",
    "Kampong Chhnang, Rolea B'ier",
    "Kampong Chhnang, Sameakki Mean Chey",
    "Kampong Chhnang, Tuek Phos",

    "Kampong Speu, Odongk Maechay City",
    "Kampong Speu, Basedth",
    "Kampong Speu, Kong Pisei",
    "Kampong Speu, Aural",
    "Kampong Speu, Phnum Sruoch",
    "Kampong Speu, Samraong Tong",
    "Kampong Speu, Thpong",
    "Kampong Speu, Chbar Mon",
    "Kampong Speu, Samkkei Munichay",

    "Kampong Thom, Stueng Saen City",
    "Kampong Thom, Baray",
    "Kampong Thom, Kampong Svay",
    "Kampong Thom, Prasat Sambour",
    "Kampong Thom, Prasat Ballangk",
    "Kampong Thom, Sandan",
    "Kampong Thom, Santuk",
    "Kampong Thom, Stoung",
    "Kampong Thom, Taing Kouk",

    "Kampot, Kampot City",
    "Kampot, Bokor City",
    "Kampot, Angkor Chey",
    "Kampot, Banteay Meas",
    "Kampot, Chhuk",
    "Kampot, Chum Kiri",
    "Kampot, Dang Tong",
    "Kampot, Kampong Trach",
    "Kampot, Tuek Chhou",

    "Kandal, Ta Khmau City",
    "Kandal, Sampeou Poun City",
    "Kandal, Akreiy Ksatr City",
    "Kandal, Kandal Stueng",
    "Kandal, Kien Svay",
    "Kandal, Khsach Kandal",
    "Kandal, Kaoh Thum",
    "Kandal, Leuk Daek",
    "Kandal, Lvea Aem",
    "Kandal, Mukh Kampul",
    "Kandal, Angk Snuol",
    "Kandal, Ponhea Lueu",
    "Kandal, S'ang",

    "Kep, Kaeb City",
    "Kep, Damnak Chang'aeur",

    "Kos Kong, Khemara Phoumin City",
    "Kos Kong, Botum Sakor",
    "Kos Kong, Kiri Sakor",
    "Kos Kong, Kaoh Kong",
    "Kos Kong, Mondol Seima",
    "Kos Kong, Srae Ambel",
    "Kos Kong, Thma Bang",

    "Kratie, Kracheh City",
    "Kratie, Chhloung",
    "Kratie, Prek Prasab",
    "Kratie, Sambour",
    "Kratie, Snuol",
    "Kratie, Chetr Borei",
    "Kratie, Ou Krieng Saenchey",

    "Mondulkiri, Saen Monourom City",
    "Mondulkiri, Kaev Seima",
    "Mondulkiri, Kaoh Nheaek",
    "Mondulkiri, Ou Reang",
    "Mondulkiri, Pech Chreada",

    "Oddar Meanchey, Samraong City",
    "Oddar Meanchey, Anlong Veaeng",
    "Oddar Meanchey, Banteay Ampil",
    "Oddar Meanchey, Chong Kal",
    "Oddar Meanchey, Trapeang Prasat",

    "Pailin, Pailin City",
    "Pailin, Sala Krau",

    "Preah Vihear, Preah Vihear City",
    "Preah Vihear, Chey Saen",
    "Preah Vihear, Chhaeb",
    "Preah Vihear, Choam Ksant",
    "Preah Vihear, Kuleaen",
    "Preah Vihear, Rovieng",
    "Preah Vihear, Sangkum Thmei",
    "Preah Vihear, Tbaeng Mean Chey",

    "Pursat, Pursat City",
    "Pursat, Bakan",
    "Pursat, Kandieng",
    "Pursat, Krakor",
    "Pursat, Phnum Kravanh",
    "Pursat, Veal Veaeng",
    "Pursat, Ta Lou Senchey",

    "Prey Veng, Prey Veng City",
    "Prey Veng, Ba Phnum",
    "Prey Veng, Kamchay Mear",
    "Prey Veng, Kampong Trabaek",
    "Prey Veng, Kanhchriech",
    "Prey Veng, Me Sang",
    "Prey Veng, Peam Chor",
    "Prey Veng, Peam Ro",
    "Prey Veng, Pea Reang",
    "Prey Veng, Preah Sdach",
    "Prey Veng, Pur Rieng",
    "Prey Veng, Sithor Kandal",
    "Prey Veng, Svay Antor",

    "Ratanakiri, Ban Lung City",
    "Ratanakiri, Andoung Meas",
    "Ratanakiri, Bar Kaev",
    "Ratanakiri, Koun Mom",
    "Ratanakiri, Lumphat",
    "Ratanakiri, Ou Chum",
    "Ratanakiri, Ou Ya Dav",
    "Ratanakiri, Ta Veaeng",
    "Ratanakiri, Veun Sai",

    "Preah Sihanouk, Preah Sihanouk City",
    "Preah Sihanouk, Kaoh Rung City",
    "Preah Sihanouk, Prey Nob",
    "Preah Sihanouk, Stueng Hav",
    "Preah Sihanouk, Kampong Seila",

    "Stung Treng, Stung Treng City",
    "Stung Treng, Sesan",
    "Stung Treng, Siem Bouk",
    "Stung Treng, Siem Pang",
    "Stung Treng, Thala Barivat",
    "Stung Treng, Borei Ou Svay Senchey",

    "Svay Rieng, Svay Rieng City",
    "Svay Rieng, Bavet City",
    "Svay Rieng, Chantrea",
    "Svay Rieng, Kampong Rou",
    "Svay Rieng, Rumduol",
    "Svay Rieng, Romeas Haek",
    "Svay Rieng, Svay Chrum",
    "Svay Rieng, Svay Teab",

    "Takeo, Doun Kaev City",
    "Takeo, Angkor Borei",
    "Takeo, Bati",
    "Takeo, Borei Cholsar",
    "Takeo, Kiri Vong",
    "Takeo, Kaoh Andaet",
    "Takeo, Prey Kabbas",
    "Takeo, Samraong",
    "Takeo, Tram Kak",
    "Takeo, Treang",

    "Tboung Khmum, Suong City",
    "Tboung Khmum, Dambae",
    "Tboung Khmum, Krouch Chhmar",
    "Tboung Khmum, Memot",
    "Tboung Khmum, Ou Reang Ov",
    "Tboung Khmum, Ponhea Kraek",
    "Tboung Khmum, Tboung Khmum",

    
];

module.exports = {khmerAddresses};
  