import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex-grow relative">
        <div
          className="h-fit w-full overflow-hidden bg-cover bg-fixed bg-left bg-no-repeat"
          style={{
            backgroundImage:
              "url('https://a.cdn-hotels.com/gdcs/production66/d41/07b19af0-8ab2-492e-97af-1ba8c6cac50a.jpg')",
          }}
        >
          <Header />
          <main className="flex-grow">{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
